
import { GoogleGenAI } from "@google/genai";

const getClient = () => {
  // Use globalThis to safely access process in any environment (Browser/Node)
  // This prevents 'Uncaught ReferenceError: process is not defined' if the polyfill is bypassed or delayed.
  // We check multiple fallback locations for the API key.
  let apiKey = '';
  try {
     const pEnv = (globalThis as any).process?.env || (window as any).process?.env || {};
     apiKey = pEnv.API_KEY || '';
  } catch (e) {
     console.warn("Could not access process.env", e);
  }
  
  // Return instance even if key is missing (it will fail on call, not on instantiation if handled, 
  // but GoogleGenAI constructor might throw if key is missing depending on version. 
  // The official docs say it takes {apiKey}. If missing, we throw here to be clear.)
  if (!apiKey) {
    throw new Error("API Key not found. Please ensure process.env.API_KEY is configured.");
  }
  return new GoogleGenAI({ apiKey });
};

/**
 * Edits or generates an image based on a source image and a text prompt.
 * Uses the Nano Banana model (gemini-2.5-flash-image) as requested.
 */
export const editImageWithGemini = async (
  imageInput: string,
  prompt: string
): Promise<string> => {
  try {
    const ai = getClient();
    
    const parts: any[] = [
      { text: prompt }
    ];

    // Check if the input is a valid Data URI (Base64)
    if (imageInput && imageInput.startsWith('data:')) {
      // Extract MIME type
      const mimeMatch = imageInput.match(/^data:(image\/[a-zA-Z+]+);base64,/);
      const mimeType = mimeMatch ? mimeMatch[1] : 'image/png'; // Default to png if parsing fails but starts with data:
      
      // Extract Base64 data
      const base64Data = imageInput.replace(/^data:image\/[a-zA-Z+]+;base64,/, "");
      
      parts.push({
        inlineData: {
          mimeType: mimeType,
          data: base64Data,
        },
      });
    } 
    // If it is a URL (e.g. https://picsum.photos...), we do not include it as inlineData 
    // because we cannot guarantee we can fetch it (CORS) or that the API accepts URLs in this context.
    // In this case, we treat it as a text-to-image generation request using the prompt.

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: parts,
      },
    });

    // Extract the image from the response
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          // The API returns raw base64 data. We need to prefix it for the browser.
          // Use the MIME type from the response if available, otherwise default to png.
          const mimeType = part.inlineData.mimeType || 'image/png';
          return `data:${mimeType};base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by Gemini.");

  } catch (error) {
    console.error("Gemini Image Generation Error:", error);
    throw error;
  }
};
